### PR TITLE
better error responses

### PR DESCRIPTION
**Pull request by wulfithewulf**
I had some issues finding the error in a rather big hosts file, so I added some useful information to the error messages.

I also had to change the error type, because of this. This may be considered a breaking change, so there may be a new major version required

### CODE REVIEW

**Comment by aneeshdurg** [comment]
Thanks for opening this, I'll review this over the weekend - I think bumping up the major version seems reasonable

**Comment by aneeshdurg** [comment]
Overall the changes make sense, but I think we should go ahead and include the linenumber  (and maybe character position where relevant) - unfortunately that requires a bit of non-trivial refactoring - we won't be able to just use `FromStr`. I'm okay with not doing that as part of this PR if you don't have the bandwidth

I'd like for this PR to bump up the major version in Cargo.toml before merging though.

**Comment by wulfithewulf** [comment]
I have included some refactoring to include the line number. 
The `FromStr`implementation does not need the line information, because its intended use is for single line parsing anyways.

I guess we could formalize the errors a bit more by defining a struct with proper enrichment of information or something similar, that may make it easier for character position. But that would need some bigger refactoring, as you said already.

Either way my feeling is, that we may keep the `FromStr`. If I have some free time again I will definitely look into it 👍

**Review by aneeshdurg — APPROVED** [review]
This is great, thank you!

**Pull request merged**
